### ISSUE TITLE
Add highlight for WinSeparator

### ISSUE THREAD

**Issue by fingolfin19** [fynnfluegge/monet.nvim#4]
Nvim is deprecating VertSplit and moving to WinSeparator for window borders in 0.10. By default, WinSeparator links to normal which does not look great for most colorschemes.

**Comment by fynnfluegge** [comment]
@fingolfin19 nice catch, thanks for the hint!

**Comment by fynnfluegge** [comment]
Fixed with https://github.com/fynnfluegge/monet.nvim/commit/d124422eb3eb27c9dffc27a4ed0e535377486d7d
