### ISSUE TITLE
add styling for markdown

### ISSUE THREAD

**Issue by chrisgrieser** [fynnfluegge/monet.nvim#5]
Thanks for the lovely theme.

It looks like the theme has no proper support for markdown? Like, when opening a markdown note, pretty much everything in plain white except URLs.

![Pasted image 2024-03-04 at 23 13 44@2x](https://github.com/fynnfluegge/monet.nvim/assets/73286100/de0da2fa-7483-475f-b8a3-455ac0ef02a3)

(the background color for the headings only comes from headlines.nvim)

**Comment by fynnfluegge** [comment]
<img width="832" alt="Screenshot 2024-04-28 at 12 17 42" src="https://github.com/fynnfluegge/monet.nvim/assets/16321871/650b6b46-4979-4f1e-9828-1e0a63b0c1ad">

How about this 🙂

**Comment by fynnfluegge** [comment]
Closed with https://github.com/fynnfluegge/monet.nvim/commit/6a3ce156c37c73341791a334fcc6e04fa902b7e4

**Comment by chrisgrieser** [comment]
nice, thank you!
